# Generated by Django 5.1.6 on 2025-02-12 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_record_macaddress_record_devicename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='MacAddress',
        ),
    ]
