# Generated by Django 5.0.6 on 2025-02-07 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_date_record_description_alter_record_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
    ]
