# Generated by Django 5.1.6 on 2025-02-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_record_macaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='deviceName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
