# Generated by Django 5.1.6 on 2025-02-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_record_devicename'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='ipAddress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
